name: java dev
description: Java enviroment. JDK + jenv + mvn
dependencies: []
commands:
  - command: sh install_mac.sh
    os: brew
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/conf.d/jenv.fish
