name: hl
description: JSON-logs reader
dependencies: []
packages:
  specific:
    - name: hl
      manager: brew
commands:
  - command: eget pamburus/hl
    os: apt
dotfiles:
  - source: dotfiles/config.yaml
    destination: ~/.config/hl/config.yaml
