name: btop
description: Resource monitor
dependencies: []
packages:
  specific:
    - name: btop
      manager: brew
commands:
  - command: eget aristocratos/btop
    os: apt
dotfiles:
  - source: dotfiles/btop.conf
    destination: ~/.config/btop/btop.conf
  - source: dotfiles/catppuccin_frappe.theme
    destination: ~/.config/btop/themes/catppuccin_frappe.theme
