name: starship
description: shell prompt
dependencies: []
packages:
  specific:
    - name: starship
      manager: brew
commands:
  - command: curl -sS https://starship.rs/install.sh | sh
    os: apt
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/conf.d/starship.fish
  - source: dotfiles/config.toml
    destination: ~/.config/starship.toml
