name: fd
description: user-friendly alternative to 'find'
dependencies: []
commands:
  - command: brew install fd && sh install.sh
    os: brew
  - command: eget sharkdp/fd && sh install.sh
    os: apt
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/conf.d/fd.fish
