alias gll "git pull"
alias gp "git push"
alias gf "git fetch --all --prune"
alias gc "git commit"
alias gl "git lg"
alias gm "git merge"
alias ga "git add"
alias gco "git checkout"
alias gss "git status -s"
