name: zoxide
description: smarter cd command
dependencies: []
packages:
  specific:
    - name: zoxide
      manager: brew
commands:
  - command: eget ajeetdsouza/zoxide
    os: apt
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/conf.d/zoxide.fish
