# General Alias
alias l='exa --long --header --group --all --group-directories-first --icons'
alias lt='l --tree'
alias lg='l --git'

alias rsync='rsync -avzhProg --ignore-existing'
alias mem_free='sudo sh -c "free -h; sudo echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a; free -h"'
