# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/zsh-config/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$ZSH/../customs"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
export plugins=(
   # Include
   autojump # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/autojump
   colored-man-pages # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/colored-man-pages
   colorize # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/colorize
   command-not-found  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/command-not-found
   common-aliases # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/common-aliases
   copybuffer  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/copybuffer
   direnv  # https://github.com/direnv/direnv
   docker # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker
   extract # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/extract
   fancy-ctrl-z  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fancy-ctrl-z
   fd  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fd
   fzf # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf
   git  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git#functions
   gitignore # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gitignore
   httpie # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/httpie
   pip # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pip
   safe-paste # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/safe-paste
   sudo # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sudo
   systemadmin # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/systemadmin

   # Third-party
   zsh-autosuggestions # https://github.com/zsh-users/zsh-autosuggestions
   zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
P10K_CONFIG="$ZSH_CUSTOM/themes/p10k.zsh"
if [ -f $P10K_CONFIG ]; then
   source $P10K_CONFIG
fi

# Genetal Alias
ALIAS_PATH="$HOME/.config/bash/bash_aliases"
if [ -f $ALIAS_PATH ]; then
   . $ALIAS_PATH
fi

# Specific Alias
ALIAS_HOST_PATH="$HOME/.bash_aliases"
if [ -f $ALIAS_HOST_PATH ]; then
   . $ALIAS_HOST_PATH
fi

# To customize prompt, run `p10k configure` or edit ~/.config/zsh-config/customs/themes/p10k.zsh.
[[ ! -f ~/.config/zsh-config/customs/themes/p10k.zsh ]] || source ~/.config/zsh-config/customs/themes/p10k.zsh

# PLUGINS CONFIG
   # Colorize
ZSH_COLORIZE_TOOL=pygmentize
ZSH_COLORIZE_STYLE="material"

   # fzf
FZF_BASE="$HOME/.fzf"
FZF_RC="$HOME/.fzf.zsh"
[ -f $FZF_RC ] && source $FZF_RC

    # autojump
AUTOJUMP_PROFILE="$HOME/.autojump/etc/profile.d/autojump.sh"
[[ -s $AUTOJUMP_PROFILE ]] && source $AUTOJUMP_PROFILE
autoload -U compinit && compinit -u

# Extend rc
EXTEND_RC="$HOME/.config/zsh/zshrc"
if [ -f $EXTEND_RC ]; then
    source $EXTEND_RC
fi
