name: kitty
description: Terminal emulator
dependencies: []
commands:
  - command: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    os: ""
dotfiles:
  - source: dotfiles/theme.conf
    destination: ~/.config/kitty/themes/theme.conf
  - source: dotfiles/kitty.conf
    destination: .config/kitty/kitty.conf
